renames social post module
localgovdrupal/localgov_elections_reporting pull request #63
Opened 2024-06-12 11:27 UTC by markconroy

Closes #62

2024-06-14 09:28 UTC, dedavidson approved these changes
Tested locally and all works.

Assume existing installs will need to uninstall sub-module before applying update? So it will be "breaking" change?

2024-06-14 09:33 UTC, markconroy commented
@dedavidson I think we probably know who is using this module at the moment, so maybe message each to ask them to uninstall it if they have it installed?

Failing that, I guess we can come up with a step-by-step

1. mark old module deprecated
2. uninstall old module
3. install new module
4. next release remove old module

2024-06-14 10:08 UTC, dedavidson commented
@markconroy sounds like a plan. Just need to make clear in release notes and promote on slack

2024-06-17 10:44 UTC, markconroy commented
PR updated to 

1. Leave the original module in place
2. Mark the original module as deprecated
3. Uninstall the original module if the new module is being installed

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

2024-06-17 19:30 UTC, finnlewis commented
@dedavidson I was just commenting on the issue, see https://github.com/localgovdrupal/localgov_elections_reporting/issues/62#issuecomment-2174255920

Might we want to take this opportunity to rename modules to be consistent with parent / child naming conventions? 

localgov_elections_reporting
localgov_elections_reporting_soical_posts

or even rename the parent module to 

localgov_elections
localgov_elections_social_posts

2024-06-17 22:42 UTC, willguv commented
I'm in favour of localgov_elections if it's not too much work

2024-06-18 08:17 UTC, dedavidson commented
I'd prefer to keep reporting or something similar in the name as the module doesn't run elections it just reports on them.

2024-06-18 11:19 UTC, finnlewis commented
Discussing in Merge Tuesday, we would like to have a breakout meeting about this. 

Do we have time to rename things now and save tech debt?

2024-06-18 15:15 UTC, dedavidson commented on modules/localgov_elections_reporting_social_post/localgov_elections_reporting_social_post.info.yml
> +package: Localgov Elections Reporting
This needs to be changed to "LocalGov Drupal"

2024-06-18 15:22 UTC, dedavidson requested changes
Package for new module needs changed but otherwise all good from local testing

2024-06-18 16:15 UTC, markconroy commented
Hi @dedavidson 

That change is made now, can you give this one final check and mark it approved if you're happy with it.

2024-06-19 08:14 UTC, dedavidson approved these changes
All good.

2024-06-19 08:20 UTC, merged